package br.edu.ufcg.dsc.opi.school;

public enum Grades {
	// @formatter:off
	FIRST_ELEMENTARY, 
	SECOND_ELEMENTARY, 
	THIRD_ELEMENTARY, 
	FOURTH_ELEMENTARY, 
	FIFTH_ELEMENTARY, 
	SIXTH_ELEMENTARY, 
	SEVENTH_ELEMENTARY, 
	EIGHTH_ELEMENTARY, 
	NINTH_ELEMENTARY, 

	FIRST_HIGH, 
	SECOND_HIGH, 
	THIRD_HIGH, 
	FOURTH_HIGH,

	FIRST_HIGHER, 
	SECOND_HIGHER, 
	THIRD_HIGHER, 
	FOURTH_HIGHER, 
	FIFTH_HIGHER, 
	SIXTH_HIGHER, 
	SEVENTH_HIGHER, 
	EIGHTH_HIGHER, 
	NINTH_HIGHER,
	TENTH_HIGHER,
	ELEVENTH_HIGHER,
	TWELFTH_HIGHER,
	THIRTEENTH_HIGHER,
	FOURTEENTH_HIGHER
	// @formatter:on
}
